# Generated by Django 4.2 on 2023-04-22 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_remove_bids_current_bid_remove_post_bid_bids_amount_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='subjects',
            new_name='subject',
        ),
    ]
