# Generated by Django 4.2 on 2023-04-23 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_rename_subjects_category_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bids',
            name='post',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='posts_bid', to='shop.post'),
        ),
    ]
