# Generated by Django 4.2 on 2023-04-29 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-title',)},
        ),
    ]
